import json

# Define the cells for the Jupyter notebook
cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 🎓 SECE Hybrid RAG AI Chatbot Assistant\n",
            "This notebook implements a complete **Retrieval-Augmented Generation (RAG)** chatbot for **Sri Eshwar College of Engineering (SECE)**, Coimbatore. \n",
            "\n",
            "### Architecture & Backend Options:\n",
            "1. **Option A: Groq + Local Embeddings (Recommended)**\n",
            "   - Uses local `SentenceTransformer` (`all-MiniLM-L6-v2`) to embed chunks and queries locally and for free.\n",
            "   - Uses **Groq** (`llama-3.3-70b-versatile`) to generate answers.\n",
            "2. **Option B: Gemini Cloud (Original)**\n",
            "   - Uses Gemini `text-embedding-004` (with automatic fallback to `embedding-001` if unavailable) for cloud embeddings.\n",
            "   - Uses **Gemini 1.5 Flash** (`gemini-1.5-flash`) to generate answers.\n",
            "\n",
            "### Features:\n",
            "- **Web Scraping**: Merges homepage text from `sece.ac.in` with a highly detailed hardcoded knowledge base.\n",
            "- **Overlap Chunking**: Custom word chunker (150 words per segment, 20 words overlap).\n",
            "- **FAISS with Cosine Similarity**: Embeddings are L2 normalized, performing exact Cosine Similarity queries using Inner Product.\n",
            "- **Gradio UI**: Modern gold & slate theme, settings configuration, quick-ask sample questions, and a live **Retrieval Inspector** showing similarity scores."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Install required libraries\n",
            "!pip install google-generativeai groq sentence-transformers faiss-cpu gradio requests beautifulsoup4 numpy --quiet"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import os\n",
            "import re\n",
            "import requests\n",
            "import numpy as np\n",
            "import faiss\n",
            "import gradio as gr\n",
            "from bs4 import BeautifulSoup\n",
            "import google.generativeai as genai\n",
            "from groq import Groq\n",
            "from sentence_transformers import SentenceTransformer\n",
            "\n",
            "# Constants\n",
            "SECE_URL = \"https://sece.ac.in\"\n",
            "TXT_FILE = \"sece_knowledge_base.txt\""
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 1. Predefined SECE Knowledge Base\n",
            "Covers Admissions, Departments, Placements, Innovation, International alliances, Contact, and General information."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "SECE_PREDEFINED_KB = [\n",
            "    \"\"\"About Sri Eshwar College of Engineering (SECE):\n",
            "Location: Coimbatore, Tamil Nadu, India.\n",
            "TEA Code: The college code for Tamil Nadu Engineering Admissions (TNEA) is 2739 (TEA Code 2739).\n",
            "Affiliation & Approval: Sri Eshwar College of Engineering (SECE) is affiliated to Anna University, Chennai, and is approved by the All India Council for Technical Education (AICTE), New Delhi. It is a premium engineering college known for academic excellence.\"\"\",\n",
            "\n",
            "    \"\"\"Departments at Sri Eshwar College of Engineering (SECE):\n",
            "The college offers 12 specialized departments:\n",
            "1. CSE-AIML: Computer Science and Engineering (Artificial Intelligence and Machine Learning)\n",
            "2. AI&DS: Artificial Intelligence and Data Science\n",
            "3. CSE: Computer Science and Engineering\n",
            "4. Cyber Security: Computer Science and Engineering (Cyber Security)\n",
            "5. CBS: Computer Science and Business Systems\n",
            "6. CCE: Computer Science and Communication Engineering\n",
            "7. ECE: Electronics and Communication Engineering\n",
            "8. VLSI: Electronics and Communication Engineering (VLSI Design and Technology)\n",
            "9. EEE: Electrical and Electronics Engineering\n",
            "10. IT: Information Technology\n",
            "11. MECH: Mechanical Engineering\n",
            "12. S&H: Department of Science and Humanities (supporting first-year studies)\"\"\",\n",
            "\n",
            "    \"\"\"Admissions at Sri Eshwar College of Engineering (SECE):\n",
            "Admissions Process: Admissions are open for the academic year 2025 (Admission 2025 open).\n",
            "Counselling Route: Students can secure admissions through the Tamil Nadu Engineering Admissions (TNEA) single-window counselling using the TEA code 2739.\n",
            "Management Quota: Seats are also available under the management quota for direct admissions for eligible candidates.\"\"\",\n",
            "\n",
            "    \"\"\"Academics at Sri Eshwar College of Engineering (SECE):\n",
            "Curriculum: The college follows the regulations and curriculum prescribed by Anna University, Chennai. The active regulations implemented are R2021 and R2823 (R2021/R2823 curriculum).\n",
            "ERP Portal: Academic records, attendance, internal test marks, and student profiles are managed via the Enterprise Resource Planning portal at erp.sece.ac.in.\"\"\",\n",
            "\n",
            "    \"\"\"Research and Development at Sri Eshwar College of Engineering (SECE):\n",
            "Research Centre: SECE has a dedicated Centre for Research that coordinates academic and industrial research projects.\n",
            "Intellectual Property Rights: The active IPR Cell assists faculty, researchers, and students in filing patents and commercializing innovations.\n",
            "Grants & Projects: The institution regularly receives research grants, seed funds for novel proposals, and undertakes industry-sponsored consultancy projects.\"\"\",\n",
            "\n",
            "    \"\"\"Innovation and Startup Ecosystem at Sri Eshwar College of Engineering (SECE):\n",
            "Innovation Hub: The college promotes creativity through the Centre for Innovation, Centres of Excellence (Cofs), and the Institution's Innovation Council (IIC).\n",
            "Hackathons: Students participate in and host several national-level and state-level hackathons.\n",
            "Ignite Startup Accelerator: The Ignite Startup Accelerator provides mentorship, infrastructure, and seed funding guidance to help students launch their startups directly from campus.\"\"\",\n",
            "\n",
            "    \"\"\"Training and Placements at Sri Eshwar College of Engineering (SECE):\n",
            "Placements Cell: The Centre for Training & Placements handles career development.\n",
            "Training Programs: SECE offers continuous training starting from the first year, including comprehensive aptitude training, programming skills development, mock interviews, and communication training.\n",
            "Recruiters: Top recruiters from multi-national corporations (MNCs), product development firms, and core engineering industries recruit students from SECE each year.\"\"\",\n",
            "\n",
            "    \"\"\"International Relations and Alliances at Sri Eshwar College of Engineering (SECE):\n",
            "Global Alliances: SECE has collaborated with reputed international universities and global research organizations.\n",
            "Opportunities: Students can opt for semester abroad programs, international internships, and inward/outward student and faculty mobility programs to gain global experience.\"\"\",\n",
            "\n",
            "    \"\"\"Campus Facilities and Infrastructure at Sri Eshwar College of Engineering (SECE):\n",
            "Infrastructure Details:\n",
            "- Smart Classrooms: Digital and interactive classrooms with audio-visual equipment.\n",
            "- Central Library: Fully automated library containing thousands of books, international journals, and digital library resources.\n",
            "- Sports: Comprehensive outdoor playgrounds, running tracks, and indoor sports complexes.\n",
            "- Hostel: Clean, safe separate hostels for boys and girls with hygienic food and high-speed Wi-Fi.\n",
            "- Wi-Fi Campus: High-speed Wi-Fi connectivity across the entire campus.\n",
            "- Medical: On-campus medical facility with a resident doctor and ambulance.\"\"\",\n",
            "\n",
            "    \"\"\"Contact and Portals for Sri Eshwar College of Engineering (SECE):\n",
            "- Official Website: sece.ac.in\n",
            "- Alumni Association Portal: alumni.sece.ac.in\n",
            "- Virtual Campus Tour: campustour.sece.ac.in\"\"\"\n",
            "]"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 2. Custom Chunker and Web Scraper\n",
            "Chunks are word-based (150 words size, 20 words overlap)."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def scrape_sece():\n",
            "    print(\"Scraping https://sece.ac.in...\")\n",
            "    headers = {\"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36\"}\n",
            "    scraped_text = \"\"\n",
            "    try:\n",
            "        res = requests.get(\"https://sece.ac.in\", headers=headers, timeout=12)\n",
            "        if res.status_code == 200:\n",
            "            soup = BeautifulSoup(res.text, \"html.parser\")\n",
            "            for tag in soup([\"script\", \"style\", \"noscript\", \"meta\", \"link\", \"header\", \"footer\", \"nav\"]):\n",
            "                tag.decompose()\n",
            "            \n",
            "            lines = [line.strip() for line in soup.get_text(separator=\"\\n\").splitlines() if line.strip()]\n",
            "            scraped_text = \"\\n\".join(lines)\n",
            "            print(f\"Scraped {len(scraped_text)} characters.\")\n",
            "        else:\n",
            "            print(f\"Scraped returned code {res.status_code}\")\n",
            "    except Exception as e:\n",
            "        print(f\"Scraping failed: {e}. Using pre-defined knowledge base only.\")\n",
            "    return scraped_text\n",
            "\n",
            "def chunk_text(text, chunk_size=150, overlap=20):\n",
            "    words = text.split()\n",
            "    chunks = []\n",
            "    step = chunk_size - overlap\n",
            "    \n",
            "    if len(words) <= chunk_size:\n",
            "        return [\" \".join(words)]\n",
            "        \n",
            "    for i in range(0, len(words), step):\n",
            "        chunk_words = words[i:i + chunk_size]\n",
            "        if chunk_words:\n",
            "            chunks.append(\" \".join(chunk_words))\n",
            "        if i + chunk_size >= len(words):\n",
            "            break\n",
            "    return chunks\n",
            "\n",
            "def prepare_all_chunks():\n",
            "    all_chunks = []\n",
            "    for doc in SECE_PREDEFINED_KB:\n",
            "        all_chunks.extend(chunk_text(doc, chunk_size=150, overlap=20))\n",
            "    scraped = scrape_sece()\n",
            "    if scraped:\n",
            "        all_chunks.extend(chunk_text(scraped, chunk_size=150, overlap=20))\n",
            "    print(f\"Total chunks created: {len(all_chunks)}\")\n",
            "    return all_chunks"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 3. Embeddings & FAISS Vector Index (Cosine Similarity)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "class HybridEmbeddings:\n",
            "    def __init__(self, mode=\"local\", gemini_model=\"models/text-embedding-004\"):\n",
            "        self.mode = mode\n",
            "        self.gemini_model = gemini_model\n",
            "        self.local_model = None\n",
            "\n",
            "    def set_mode(self, mode):\n",
            "        self.mode = mode\n",
            "        if mode == \"local\" and self.local_model is None:\n",
            "            print(\"Loading local SentenceTransformer (all-MiniLM-L6-v2)...\")\n",
            "            self.local_model = SentenceTransformer(\"all-MiniLM-L6-v2\")\n",
            "\n",
            "    def get_embeddings(self, texts, is_query=False):\n",
            "        if self.mode == \"local\":\n",
            "            if self.local_model is None:\n",
            "                self.local_model = SentenceTransformer(\"all-MiniLM-L6-v2\")\n",
            "            embeddings = self.local_model.encode(texts, convert_to_numpy=True)\n",
            "            return np.array(embeddings, dtype=\"float32\")\n",
            "        else:\n",
            "            task_type = \"retrieval_query\" if is_query else \"retrieval_document\"\n",
            "            if isinstance(texts, str):\n",
            "                try:\n",
            "                    response = genai.embed_content(model=self.gemini_model, content=texts, task_type=task_type)\n",
                    "                    return np.array(response[\"embedding\"], dtype=\"float32\")\n",
            "                except Exception as e:\n",
            "                    if \"text-embedding-004\" in self.gemini_model:\n",
            "                        print(\"v4 failed, falling back to embedding-001...\")\n",
            "                        self.gemini_model = \"models/embedding-001\"\n",
            "                        response = genai.embed_content(model=self.gemini_model, content=texts, task_type=task_type)\n",
            "                        return np.array(response[\"embedding\"], dtype=\"float32\")\n",
            "                    raise e\n",
            "            \n",
            "            embeddings = []\n",
            "            batch_size = 100\n",
            "            for i in range(0, len(texts), batch_size):\n",
            "                batch = texts[i:i + batch_size]\n",
            "                try:\n",
            "                    response = genai.embed_content(model=self.gemini_model, content=batch, task_type=task_type)\n",
            "                    embeddings.extend(response[\"embedding\"])\n",
            "                except Exception as e:\n",
            "                    if \"text-embedding-004\" in self.gemini_model:\n",
            "                        self.gemini_model = \"models/embedding-001\"\n",
            "                        return self.get_embeddings(texts, is_query=is_query)\n",
            "                    raise e\n",
            "            return np.array(embeddings, dtype=\"float32\")\n",
            "\n",
            "class HybridVectorStore:\n",
            "    def __init__(self, embedding_mode=\"local\"):\n",
            "        self.embeddings = HybridEmbeddings(mode=embedding_mode)\n",
            "        self.chunks = []\n",
            "        self.index = None\n",
            "\n",
            "    def get_index_paths(self):\n",
            "        suffix = \"local\" if self.embeddings.mode == \"local\" else \"gemini\"\n",
            "        return f\"sece_faiss_{suffix}.index\", f\"sece_chunks_{suffix}.npy\"\n",
            "\n",
            "    def build_index(self, chunks):\n",
            "        self.chunks = chunks\n",
            "        embeddings = self.embeddings.get_embeddings(chunks, is_query=False)\n",
            "        \n",
            "        # Normalize for Cosine Similarity\n",
            "        faiss.normalize_L2(embeddings)\n",
            "        dimension = embeddings.shape[1]\n",
            "        \n",
            "        self.index = faiss.IndexFlatIP(dimension)\n",
            "        self.index.add(embeddings)\n",
            "        \n",
            "        index_path, chunks_path = self.get_index_paths()\n",
            "        faiss.write_index(self.index, index_path)\n",
            "        np.save(chunks_path, np.array(self.chunks, dtype=object))\n",
            "        print(f\"Index saved to {index_path}.\")\n",
            "\n",
            "    def load_index(self):\n",
            "        index_path, chunks_path = self.get_index_paths()\n",
            "        if os.path.exists(index_path) and os.path.exists(chunks_path):\n",
            "            self.index = faiss.read_index(index_path)\n",
            "            self.chunks = np.load(chunks_path, allow_pickle=True).tolist()\n",
            "            return True\n",
            "        return False\n",
            "\n",
            "    def search(self, query, k=4):\n",
            "        if self.index is None:\n",
            "            return []\n",
            "        query_emb = self.embeddings.get_embeddings(query, is_query=True)\n",
            "        if len(query_emb.shape) == 1:\n",
            "            query_emb = query_emb.reshape(1, -1)\n",
            "            \n",
            "        faiss.normalize_L2(query_emb)\n",
            "        scores, indices = self.index.search(query_emb, k)\n",
            "        \n",
            "        results = []\n",
            "        for score, idx in zip(scores[0], indices[0]):\n",
            "            if idx != -1 and idx < len(self.chunks):\n",
            "                results.append((self.chunks[idx], float(score)))\n",
            "        return results"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 4. RAG Chatbot Query Engine"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "class SECEChatbotEngine:\n",
            "    def __init__(self):\n",
            "        self.mode = \"groq\"\n",
            "        self.vector_store = HybridVectorStore(embedding_mode=\"local\")\n",
            "        self.groq_api_key = os.environ.get(\"GROQ_API_KEY\", \"\")\n",
            "        self.gemini_api_key = os.environ.get(\"GOOGLE_API_KEY\", \"\")\n",
            "        self.api_configured = False\n",
            "\n",
            "    def configure_engine(self, mode, api_key):\n",
            "        if not api_key:\n",
            "            return False, \"API key cannot be empty.\"\n",
            "        api_key = api_key.strip()\n",
            "        if mode == \"groq\":\n",
            "            try:\n",
            "                test_client = Groq(api_key=api_key)\n",
            "                test_client.models.list()\n",
            "                self.groq_api_key = api_key\n",
            "                os.environ[\"GROQ_API_KEY\"] = api_key\n",
            "                self.mode = \"groq\"\n",
            "                self.vector_store.embeddings.set_mode(\"local\")\n",
            "                self.api_configured = True\n",
            "                \n",
            "                if not self.vector_store.load_index():\n",
            "                    chunks = prepare_all_chunks()\n",
            "                    self.vector_store.build_index(chunks)\n",
            "                return True, \"Groq Configured!\"\n",
            "            except Exception as e:\n",
            "                return False, f\"Groq validation failed: {e}\"\n",
            "        else:\n",
            "            try:\n",
            "                genai.configure(api_key=api_key)\n",
            "                try:\n",
            "                    genai.embed_content(model=\"models/text-embedding-004\", content=\"test\", task_type=\"retrieval_query\")\n",
            "                except Exception:\n",
            "                    genai.embed_content(model=\"models/embedding-001\", content=\"test\", task_type=\"retrieval_query\")\n",
            "                self.gemini_api_key = api_key\n",
            "                os.environ[\"GOOGLE_API_KEY\"] = api_key\n",
            "                self.mode = \"gemini\"\n",
            "                self.vector_store.embeddings.set_mode(\"gemini\")\n",
            "                self.api_configured = True\n",
            "                \n",
            "                if not self.vector_store.load_index():\n",
            "                    chunks = prepare_all_chunks()\n",
            "                    self.vector_store.build_index(chunks)\n",
            "                return True, \"Gemini Configured!\"\n",
            "            except Exception as e:\n",
            "                return False, f\"Gemini validation failed: {e}\"\n",
            "\n",
            "    def generate_answer(self, query):\n",
            "        if not self.api_configured:\n",
            "            return \"Please configure your API Key in the settings first.\", []\n",
            "            \n",
            "        retrieved = self.vector_store.search(query, k=4)\n",
            "        if not retrieved:\n",
            "            return \"No context retrieved.\", []\n",
            "            \n",
            "        context_str = \"\\n\\n\".join([f\"[Source Chunk {i+1} - Similarity: {score:.4f}]\\n{text}\" for i, (text, score) in enumerate(retrieved)])\n",
            "        \n",
            "        prompt = f\"\"\"You are an assistant for Sri Eshwar College of Engineering (SECE), Coimbatore.\n",
            "Answer the user's question ONLY using the retrieved context provided below.\n",
            "If the answer cannot be found or answered using ONLY the retrieved context, you MUST output exactly:\n",
            "\"I don't have information about this in my data. Please refer to sece.ac.in for official details.\"\n",
            "\n",
            "Do not make up any information or use outside knowledge.\n",
            "\n",
            "Retrieved Context:\n",
            "{context_str}\n",
            "\n",
            "Question: {query}\n",
            "\n",
            "Answer:\"\"\"\n",
            "\n",
            "        if self.mode == \"groq\":\n",
            "            try:\n",
            "                client = Groq(api_key=self.groq_api_key)\n",
            "                completion = client.chat.completions.create(\n",
            "                    messages=[{\"role\": \"user\", \"content\": prompt}],\n",
            "                    model=\"llama-3.3-70b-versatile\",\n",
            "                    temperature=0.0\n",
            "                )\n",
            "                return completion.choices[0].message.content.strip(), retrieved\n",
            "            except Exception as e:\n",
            "                return f\"Groq generation failed: {e}\", retrieved\n",
            "        else:\n",
            "            try:\n",
            "                model = genai.GenerativeModel(\"gemini-1.5-flash\")\n",
            "                response = model.generate_content(prompt, generation_config={\"temperature\": 0.0})\n",
            "                return response.text.strip(), retrieved\n",
            "            except Exception as e:\n",
            "                return f\"Gemini generation failed: {e}\", retrieved\n",
            "\n",
            "engine = SECEChatbotEngine()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 5. Launch Gradio Dashboard App"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "custom_css = \"\"\"\n",
            "body { background-color: #0b0f19; font-family: 'Outfit', 'Inter', sans-serif; color: #f1f5f9; }\n",
            ".sece-header { text-align: center; padding: 24px; background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%); border-radius: 12px; border-bottom: 4px solid #f59e0b; margin-bottom: 24px; }\n",
            ".sece-header h1 { color: #f59e0b !important; font-weight: 800; margin: 0; font-size: 2.2rem; }\n",
            ".sece-header p { color: #94a3b8 !important; font-size: 1.1rem; margin-top: 8px; }\n",
            ".chatbot-col { background-color: #111827; border-radius: 12px; padding: 16px; border: 1px solid #1f2937; }\n",
            ".sidebar-col { background-color: #1e293b; border-radius: 12px; padding: 16px; border: 1px solid #334155; }\n",
            ".gr-button-primary { background: linear-gradient(to right, #d97706, #f59e0b) !important; border: none !important; color: white !important; font-weight: 600 !important; }\n",
            ".sources-card { background-color: #0f172a; border-left: 4px solid #f59e0b; padding: 12px; margin-bottom: 12px; border-radius: 0 8px 8px 0; }\n",
            ".sources-card h4 { margin: 0 0 6px 0; color: #fbbf24; font-size: 0.95rem; }\n",
            ".sources-card p { margin: 0; font-size: 0.85rem; color: #cbd5e1; line-height: 1.4; }\n",
            "\"\"\"\n",
            "\n",
            "SAMPLE_QUESTIONS = [\n",
            "    \"What is the TNEA code for Sri Eshwar College of Engineering and which university is it affiliated with?\",\n",
            "    \"Which departments and engineering courses are offered at SECE?\",\n",
            "    \"Can you tell me about the admissions process and if there is management quota?\",\n",
            "    \"What research facilities, grants, and startup support are available at SECE?\",\n",
            "    \"What are the top recruiters and placement support offered by the Centre for Training & Placements?\"\n",
            "]\n",
            "\n",
            "def build_app():\n",
            "    with gr.Blocks(title=\"SECE RAG AI Chatbot\") as demo:\n",
            "        gr.HTML(\"\"\"\n",
            "            <div class='sece-header'>\n",
            "                <h1>🎓 Sri Eshwar College of Engineering</h1>\n",
            "                <p>Advanced RAG Chatbot Assistant (Supporting Groq & Gemini)</p>\n",
            "            </div>\n",
            "        \"\"\")\n",
            "        \n",
            "        with gr.Row():\n",
            "            with gr.Column(scale=3, elem_classes=\"chatbot-col\"):\n",
            "                gr.Markdown(\"### 💬 Chat Assistant\")\n",
            "                chatbot = gr.Chatbot(height=450)\n",
            "                \n",
            "                with gr.Row():\n",
            "                    query_input = gr.Textbox(placeholder=\"Type your question here...\", label=\"Your Query\", scale=4)\n",
            "                    submit_btn = gr.Button(\"Submit\", variant=\"primary\", scale=1, elem_classes=\"gr-button-primary\")\n",
            "                    \n",
            "                gr.Markdown(\"#### 💡 Sample Questions\")\n",
            "                with gr.Row():\n",
            "                    for q_text in SAMPLE_QUESTIONS:\n",
            "                        gr.Button(q_text, size=\"sm\").click(\n",
            "                            fn=lambda x=q_text: x, \n",
            "                            outputs=[query_input]\n",
            "                        )\n",
            "            \n",
            "            with gr.Column(scale=2, elem_classes=\"sidebar-col\"):\n",
            "                gr.Markdown(\"### ⚙️ settings\")\n",
            "                backend_select = gr.Radio(\n",
            "                    choices=[\"Groq + Local Embeddings\", \"Gemini Cloud (Embeddings & LLM)\"],\n",
            "                    value=\"Groq + Local Embeddings\" if engine.mode == \"groq\" else \"Gemini Cloud (Embeddings & LLM)\",\n",
            "                    label=\"RAG Engine Backend\"\n",
            "                )\n",
            "                api_key_box = gr.Textbox(label=\"Active API Key\", placeholder=\"Enter Groq (gsk_...) or Gemini (AIza...) key\", type=\"password\", value=engine.groq_api_key if engine.mode == \"groq\" else engine.gemini_api_key)\n",
            "                verify_btn = gr.Button(\"Apply & Verify Config\")\n",
            "                status_text = gr.Markdown(\"🟢 Engine ready.\" if engine.api_configured else \"🔴 Configure API key to start.\")\n",
            "                \n",
            "                gr.HTML(\"<hr style='border-color: #334155; margin: 16px 0;' />\")\n",
            "                reindex_btn = gr.Button(\"Force Rebuild Vector Index\")\n",
            "                index_status = gr.Markdown(\"Index cache checks complete.\")\n",
            "                \n",
            "                gr.HTML(\"<hr style='border-color: #334155; margin: 16px 0;' />\")\n",
            "                gr.Markdown(\"### 🔍 Retrieval Inspector\")\n",
            "                inspector_panel = gr.HTML(\"<div style='color: #64748b; font-style: italic;'>Submit a question to see retrieved chunks.</div>\")\n",
            "                \n",
            "        def handle_verify(backend, key):\n",
            "            mode = \"groq\" if \"Groq\" in backend else \"gemini\"\n",
            "            success, msg = engine.configure_engine(mode, key)\n",
            "            if success:\n",
            "                return f\"🟢 Configured successfully: {engine.mode.upper()} mode!\"\n",
            "            return f\"🔴 {msg}\"\n",
            "\n",
            "        def rebuild_index():\n",
            "            try:\n",
            "                chunks = prepare_all_chunks()\n",
            "                engine.vector_store.build_index(chunks)\n",
            "                return f\"🟢 Index rebuilt successfully for {engine.mode.upper()} mode!\"\n",
            "            except Exception as e:\n",
            "                return f\"🔴 Error: {e}\"\n",
            "\n",
            "        def handle_chat(msg, history):\n",
            "            if not msg.strip():\n",
            "                return \"\", history, \"\"\n",
            "            ans, retrieved = engine.generate_answer(msg)\n",
            "            history.append({\"role\": \"user\", \"content\": msg})\n",
            "            history.append({\"role\": \"assistant\", \"content\": ans})\n",
            "            \n",
            "            inspector_html = \"\"\n",
            "            for idx, (text, score) in enumerate(retrieved, 1):\n",
            "                safe_text = text.replace(\"&\", \"&amp;\").replace(\"<\", \"&lt;\").replace(\">\", \"&gt;\").replace(\"\\n\", \"<br/>\")\n",
            "                inspector_html += f\"\"\"\n",
            "                <div class='sources-card'>\n",
            "                    <h4>Chunk {idx} — Similarity Score: <b>{score:.4f}</b></h4>\n",
            "                    <p>{safe_text}</p>\n",
            "                </div>\n",
            "                \"\"\"\n",
            "            return \"\", history, inspector_html or \"<div style='color: #ef4444;'>No chunks retrieved.</div>\"\n",
            "\n",
            "        def update_key_placeholder(backend):\n",
            "            if \"Groq\" in backend:\n",
            "                return gr.update(value=engine.groq_api_key, placeholder=\"Enter Groq Key starting with gsk_...\")\n",
            "            else:\n",
            "                return gr.update(value=engine.gemini_api_key, placeholder=\"Enter Gemini Key starting with AIza...\")\n",
            "\n",
            "        backend_select.change(update_key_placeholder, [backend_select], [api_key_box])\n",
            "        verify_btn.click(handle_verify, [backend_select, api_key_box], [status_text])\n",
            "        reindex_btn.click(rebuild_index, outputs=[index_status])\n",
            "        submit_btn.click(handle_chat, [query_input, chatbot], [query_input, chatbot, inspector_panel])\n",
            "        query_input.submit(handle_chat, [query_input, chatbot], [query_input, chatbot, inspector_panel])\n",
            "        \n",
            "    return demo\n",
            "\n",
            "# Initialize engine\n",
            "engine.auto_init_from_env()\n",
            "engine.vector_store.load_index()\n",
            "\n",
            "app = build_app()\n",
            "app.launch(share=False, css=custom_css)"
        ]
    }
]

notebook_data = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3 (ipykernel)",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

# Save the generated notebook
notebook_path = "WebScrapSECE.ipynb"
with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook_data, f, indent=2)

print(f"Jupyter Notebook successfully written to {notebook_path}")
